name: Ricktionary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: latest

    - name: Clean build folder
      run: |
        xcodebuild clean -project Ricktionary/Ricktionary.xcodeproj -scheme Ricktionary -configuration Debug

    - name: Build the app
      run: |
        xcodebuild build -project Ricktionary/Ricktionary.xcodeproj -scheme Ricktionary -sdk iphonesimulator -configuration Debug

    - name: Run unit tests
      run: |
        xcodebuild test \
          -project Ricktionary/Ricktionary.xcodeproj \
          -scheme Ricktionary \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          -configuration Debug
